### ISSUE TITLE
can't choose when to connect

### ISSUE THREAD

**Issue by jrr** [netguru/ember-pusher-guru#17]
I need to control when the pusher connection is made. (I depend on information that's not available at service init time, and sometimes I do not connect at all)

For now I'm keeping a fork of the project, with the `setup()` line commented out in `pusher-base.js`. Instead I call it from my derived service later, long after `init()`.

Is there a better way to do this with the current version of ember-pusher-guru?

If not, how could the API be changed to support this usage?

The only idea I can come up with is to put an option in the environment, kind of like `pusherKey` is now. Something like `pusherManualSetup` for users like me who want to call `setup()` manually.

If that sounds good I'll work on a PR, but I'm hoping for a better approach.

Thanks!

**Comment by jniechcial** [comment]
Thanks for your input. It looks reasonable to have such option to switch off auto connection. However, instead of setting it up in config I wonder if it won't be better to set it up as some kind of `autoConnect` variable straight in service, that by default is set to true (no regressions), but can be set to false when you `extend` the service. What do you think? Thanks to that, unit testing this should be easier also.

Also, I think we should take into consideration when the user will use any of public API (like `removeChannel` and so on). If the service is not connected, we should raise some kind of exception. But we can also take care of this work - if you want just focus on first part, unit test it and we will focus on handling edge cases. Will release both in next release.

**Comment by jrr** [comment]
Great idea! An `autoconnect` flag on the service is way cleaner than an env var. I took a stab at this and created a PR: https://github.com/netguru/ember-pusher-guru/pull/18.

**Comment by jniechcial** [comment]
Solved, thanks!
